### PR TITLE
Do not inject GTM script if ember-cli-gtm environment variable is not defined.

### PR DESCRIPTION
**Pull request by johnnyoshika**
This will allow development environment to work without loading GTM.

### CODE REVIEW

**Comment by yadomi** [comment]
+1

**Comment by johnnyoshika** [comment]
@sas1ni69: any chance you can merge this if you don't have any objections?  :-)

**Comment by piotrekbator** [comment]
👍

**Comment by johnnyoshika** [comment]
@sas1ni69 Any chance you can merge this branch?  It will take a click of a button.  :-)

**Comment by sas1ni69** [comment]
@johnnyoshika I am so sorry!!!!!!!!!!! I just saw this.

**Pull request merged**
