### PR TITLE
Only add the code if the appId is provided

### PR DESCRIPTION
**Pull request by simonexmachina**

### CODE REVIEW

**Comment by sas1ni69** [comment]
Thanks Simon 👍 appreciate it.

**Comment by simonexmachina** [comment]
No worries. One other thought is that that script tag should be `async`.

**Comment by simonexmachina** [comment]
Also, can you please advise when you publish so I can get back off my fork. Thanks!

**Comment by sas1ni69** [comment]
Good thought. I will try to get it out in the next few days and I'll ping you.

**Pull request merged**
